SRC += $(wildcard ${LIBPERIPH_DIR}/devices/internal_led/*.c) \
	   $(wildcard ${LIBPERIPH_DIR}/devices/internal_led/rgb/*.c) \
	   $(wildcard ${LIBPERIPH_DIR}/devices/internal_led/legacy/*.c)
INC += -I${LIBPERIPH_DIR}/devices/internal_led
