SRC += $(wildcard ${LIBPERIPH_DIR}/sensors/barometer/*.c) \
       $(wildcard ${LIBPERIPH_DIR}/sensors/current_sensor/*.c) \
       $(wildcard ${LIBPERIPH_DIR}/sensors/esc/*.c) \
       $(wildcard ${LIBPERIPH_DIR}/sensors/gps/*.c) \
       $(wildcard ${LIBPERIPH_DIR}/sensors/imu/*.c) \
       $(wildcard ${LIBPERIPH_DIR}/sensors/magnetometer/*.c) \
       ${LIBPERIPH_DIR}/sensors/rangefinder/garmin_lite.c \
       ${LIBPERIPH_DIR}/sensors/rangefinder/sf1xx.c \
       ${LIBPERIPH_DIR}/sensors/rangefinder/tf_luna.c \
       $(wildcard ${LIBPERIPH_DIR}/sensors/temperature_sensor/*.c)
INC += -I${REPOSITORY_PATH}/Lib/libperiph/sensors
