SRC += $(wildcard ${LIBPERIPH_DIR}/devices/rgb_leds/*.c) \
	   ${LIBPERIPH_DIR}/devices/servos.c
INC += -I${REPOSITORY_PATH}/Lib/libperiph/devices
INC += -I${REPOSITORY_PATH}/Lib/libperiph/devices/servos
