name: arm_build

on: [push]
jobs:
  arm_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install GIT
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v2
        with:
          path: 'repository'

      - name: Install dependencies
        run: sudo apt-get install -y make gcc-arm-none-eabi

      - run: cd repository && mkdir build && ./test.sh