name: unit_tests

on: [push]
jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install GIT
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: RaccoonlabDev/code_style
          token: ${{ secrets.ACCESS_TOKEN }}
          path: code_style

      - name: Install dependencies
        run: sudo apt-get install -y make gcc-arm-none-eabi

      - name: Install gtest
        run: code_style/install_gtest.sh

      - run: make unit_tests
